CREATE TABLE BundleMaster (
    BundleID INT AUTO_INCREMENT PRIMARY KEY,
    BundleName VARCHAR(255) NOT NULL,
    BundleDescription TEXT,
    ActualBundlePrice DECIMAL(10, 2) NOT NULL,
    DiscountBundlePrice DECIMAL(10, 2) NOT NULL,
    IsActive BOOLEAN DEFAULT TRUE,
    CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE BundleMapping (
    BundleMappingID INT AUTO_INCREMENT PRIMARY KEY,
    BundleID INT NOT NULL,
    ProductID INT NOT NULL,
    FOREIGN KEY (BundleID) REFERENCES BundleMaster(BundleID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES ProductMaster(ProductID) ON DELETE CASCADE
);
